spring.application.name=MarineClinic
# database config

spring.datasource.url=jdbc:mysql://localhost:3306/MarineDB2
spring.datasource.username=root
spring.datasource.password=root

# jpa
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform = org.hibernate.dialect.MySQLDialect
#spring.thymeleaf.prefix = classpath:/templates/
#spring.thymeleaf.suffix = .html

jwt.secret=vNx6LQ8QkD6r0Gm2sW3zTX7jvLWVv5P0lVbqvg4UGdM=
jwt.expiration=3600000